repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-ast
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=no]
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.10.0
    hooks:
    -   id: reorder-python-imports
        args: [--py37-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
    -   id: pyupgrade
